// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementPostLikesCount(ctx context.Context, id int64) (Post, error)
	DeletePost(ctx context.Context, id int64) error
	DeleteUserById(ctx context.Context, id int64) error
	GetCommentById(ctx context.Context, id int64) (Comment, error)
	GetPostById(ctx context.Context, id int64) (Post, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByUUID(ctx context.Context, userUuid pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementPostLikesCount(ctx context.Context, id int64) (Post, error)
	ListCommentsByPostIdOrderByCreatedAtAsc(ctx context.Context, postID int64) ([]Comment, error)
	ListCommentsByPostIdOrderByCreatedAtDesc(ctx context.Context, postID int64) ([]Comment, error)
	ListCommentsByPostIdOrderByLikesAsc(ctx context.Context, postID int64) ([]Comment, error)
	ListCommentsByPostIdOrderByLikesDesc(ctx context.Context, postID int64) ([]Comment, error)
	ListCommentsByUserIdOrderByCreateAtAsc(ctx context.Context, userID int64) ([]Comment, error)
	ListCommentsByUserIdOrderByCreateAtDesc(ctx context.Context, userID int64) ([]Comment, error)
	ListCommentsByUserIdOrderByLikesAsc(ctx context.Context, userID int64) ([]Comment, error)
	ListCommentsByUserIdOrderByLikesDesc(ctx context.Context, userID int64) ([]Comment, error)
	ListCommentsRepliesOrderByCreateAtAsc(ctx context.Context, parentCommentID pgtype.Int8) ([]Comment, error)
	ListCommentsRepliesOrderByCreateAtDesc(ctx context.Context, parentCommentID pgtype.Int8) ([]Comment, error)
	ListCommentsRepliesOrderByLikesAsc(ctx context.Context, parentCommentID pgtype.Int8) ([]Comment, error)
	ListCommentsRepliesOrderByLikesDesc(ctx context.Context, parentCommentID pgtype.Int8) ([]Comment, error)
	ListPostsByUserIdOrderByCreatedAtAsc(ctx context.Context, userID int64) ([]Post, error)
	ListPostsByUserIdOrderByCreatedAtDesc(ctx context.Context, userID int64) ([]Post, error)
	ListPostsByUserIdOrderByLikesAsc(ctx context.Context, userID int64) ([]Post, error)
	ListPostsByUserIdOrderByLikesDesc(ctx context.Context, userID int64) ([]Post, error)
	ListPostsOrderByCreatedAtAsc(ctx context.Context, arg ListPostsOrderByCreatedAtAscParams) ([]Post, error)
	ListPostsOrderByCreatedAtDesc(ctx context.Context, arg ListPostsOrderByCreatedAtDescParams) ([]Post, error)
	ListPostsOrderByLikesAtAsc(ctx context.Context, arg ListPostsOrderByLikesAtAscParams) ([]Post, error)
	ListPostsOrderByLikesAtDesc(ctx context.Context, arg ListPostsOrderByLikesAtDescParams) ([]Post, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUserEmailById(ctx context.Context, arg UpdateUserEmailByIdParams) (User, error)
	UpdateUserPasswordById(ctx context.Context, arg UpdateUserPasswordByIdParams) (User, error)
}

var _ Querier = (*Queries)(nil)
